name: "Deploy Python App"
description: "Composite action to deploy our Python Flask App using pm2"
inputs: 
  env:
    description: "Environment where to deploy Python Flask App"
    required: true
  port:
    description: "Port used by for Python Flask App"
    required: true

runs:
  using: composite
  steps:
    - name: Log message
      shell: cmd
      run: echo "Deploying the app to ${{ inputs.env }} environment..."
      
    - name: Deploy the app to ${{ inputs.env }}
      shell: cmd
      working-directory: python-greetings
      run: |
        .\.venv\Scripts\activate.bat  # Активация виртуальной среды в CMD
        pm2 delete greetings-app-${{ inputs.env }} || echo "No existing app found"  # Удаление старого приложения, если оно есть
        pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}  # Запуск нового приложения
