name: Python greetings delivery pipeline

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Installing all pip dependencies...
        working-directory: python-greetings
        run: pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
      
      - name: Stop existing service (if any)
        run: | 
          pm2 start app.py --name greetings-app-dev --port 7001
        working-directory: python-greetings
