name: Python greetings

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: cmd

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - name: Log message
        run: echo Installing all pip dependencies...
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings


      - name: Install deps step
        working-directory: python-greetings
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate.bat  # Активация виртуальной среды в CMD
          pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: python-greetings
 
      - uses: ./.github/actions/deploy
        with:
          env: 'dev'
          port: 7001


  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:

      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with:
          env: 'dev'

  deploy-to-stg:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: python-greetings
         
      - uses: ./.github/actions/deploy
        with:
          env: 'stg'
          port: 7002


  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:

      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with:
          env: 'stg'


  deploy-to-preprod:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: python-greetings
         
      - uses: ./.github/actions/deploy
        with:
          env: 'preprod'
          port: 7003


  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:

      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with:
          env: 'preprod'

  deploy-to-prod:
    runs-on: self-hosted
    needs: install-pip-deps
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mtararujs/python-greetings'
          path: python-greetings
         
      - uses: ./.github/actions/deploy
        with:
          env: 'prod'
          port: 7004

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-dev
    steps:

      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with:
          env: 'preprod'