name: Python greetings

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

defaults:
  run:
    shell: cmd  # Указываем, что нужно использовать командную строку Windows

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps: 
      - name: Log message
        run: echo Installing all pip dependencies...
      - uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
      - name: Install deps step
        working-directory: python-greetings
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate.bat  # Активация виртуальной среды в CMD
          pip install -r requirements.txt

  deploy-to-dev:
    runs-on: self-hosted
    needs: [ install-pip-deps ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'mdaugavietis/python-app'
          sparse-checkout: .github/actions
          sparse-checkout-cone-mode: false
          path: python-app
      - uses: ./python-app/.github/actions/deploy
        with:
          env: 'dev'
          port: 7001

  tests-on-dev:
    runs-on: self-hosted
    needs: [ deploy-to-dev ]
    steps:
      - uses: ./python-app/.github/actions/test
        with:
          env: 'dev'
