name: Python greetings delivery pipeline

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/build

  deploy-to-dev:
    needs: install-pip-deps
    runs-on: self-hosted
    steps:
      - name: Checkout Pipeline repo
        uses: actions/checkout@v4

      - name: Clone python-greetings repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
      
      - name: Install check
        run: npm -v
        working-directory: python-greetings



      - name: Stop existing dev service (if exists)
        run: pm2 delete greetings-app-dev & EXIT /B 0)
        shell: cmd
        working-directory: python-greetings

      - name: Start dev service
        run: pm2 start app.py --name greetings-app-dev -- --port 7001
        shell: cmd
        working-directory: python-greetings
