name: Python greetings delivery pipeline

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/build

